import { defineSkeletonClasses } from '../internal/define-skeleton-classes.js' with { type: 'macro' };

export const classesDatePicker = defineSkeletonClasses({
	root: 'flex flex-col gap-2',
	label: 'label-text',
	control: 'relative',
	input: 'input',
	trigger: 'btn-icon btn-icon-sm preset-tonal absolute end-1.5 top-1/2 -translate-y-1/2',
	clearTrigger: '',
	presetTrigger: '',
	positioner: '',
	content: 'card bg-surface-50-950 border border-surface-200-800 p-2 flex flex-col gap-2 w-full',
	yearSelect: 'select',
	monthSelect: 'select',
	view: '',
	viewControl: '',
	prevTrigger: 'btn preset-filled',
	viewTrigger: 'btn preset-filled',
	rangeText: '',
	nextTrigger: 'btn preset-filled',
	table: '',
	tableHead: '',
	tableRow: '',
	tableHeader: '',
	tableBody: '',
	tableCell: '',
	tableCellTrigger: '',
});
