import { defineSkeletonClasses } from '../internal/define-skeleton-classes.js' with { type: 'macro' };

export const classesDatePicker = defineSkeletonClasses({
	root: 'flex flex-col gap-2',
	label: 'label-text',
	control: 'relative',
	input: 'input',
	trigger: 'btn-icon btn-icon-sm preset-tonal absolute end-1.5 top-1/2 -translate-y-1/2',
	clearTrigger: '',
	presetTrigger: '',
	positioner: '',
	content: 'card bg-surface-50-950 border border-surface-200-800 p-2 flex flex-col gap-2',
	yearSelect: 'select',
	monthSelect: 'select',
	view: 'flex flex-col gap-2',
	viewControl: 'flex gap-2 justify-between',
	prevTrigger: 'btn hover:preset-tonal',
	viewTrigger: 'btn hover:preset-tonal',
	rangeText: '',
	nextTrigger: 'btn hover:preset-tonal',
	table: 'table-fixed',
	tableHead: '',
	tableRow: '',
	tableHeader: 'size-10',
	tableBody: '',
	tableCell: 'size-10',
	tableCellTrigger: 'size-full btn p-0 hover:preset-tonal',
});
