import { defineSkeletonClasses } from '../internal/define-skeleton-classes.js' with { type: 'macro' };

export const classesDatePicker = defineSkeletonClasses({
	root: 'flex flex-col gap-2',
	label: 'label-text',
	control: 'relative',
	input: 'input',
	trigger: 'btn-icon btn-icon-sm preset-tonal absolute end-1.5 top-1/2 -translate-y-1/2',
	content: '',
	monthSelect: '',
	yearSelect: '',
	rangeText: '',
	table: '',
	tableBody: '',
	tableCell: '',
	tableCellTrigger: '',
	tableHead: '',
	tableHeader: '',
	tableRow: '',
	view: '',
	viewControl: '',
	viewTrigger: '',
	clearTrigger: '',
	presetTrigger: '',
	prevTrigger: '',
	nextTrigger: '',
	positioner: '',
});
