<script lang="ts">
	// Slots:
	/** @slot trail - A label slot directly below the range slider. */

	import { afterUpdate } from 'svelte';

	// Props
	/** Set the input step offset. */
	export let value: number = 0;
	/** Set the input value. */
	export let min: number = 0;
	/** Set the input minimum range. */
	export let max: number = 100;
	/** Set the input maximum range. */
	export let step: number = 1;
	/** Enables tick marks. See browser support below. */
	export let ticked: boolean = false;
	/** Provide classes to set the input accent color. */
	export let accent: string = 'accent-token';

	// Props (a11y)
	/** Provide a unique input id. Auto generated by default */
	export let id: string = crypto.randomUUID();
	/** Provide a unique name, is set to the id by default */
	export let name: string = id;
	/** A semantic ARIA label. */
	export let label: string = '';

	// Base Styles
	const cBase: string = 'space-y-2';
	const cBaseLabel: string = '';
	const cBaseContent: string = 'flex justify-center py-2';
	const cBaseInput: string = 'w-full h-2';

	// Local
	let tickmarks: any[];

	// Tickmarks - generate datalist options based on min/max values
	function setTicks(): void {
		if (ticked == false) return;
		tickmarks = Array.from({ length: max - min + 1 }, (_, i) => i + 1);
	}

	// Lifecycle
	afterUpdate(() => {
		setTicks();
	});

	// Reactive Classes
	$: classesBase = `${cBase} ${$$props.class ?? ''}`;
	$: classesInput = `${cBaseInput} ${accent}`;

	// Prune $$restProps to avoid overwriting $$props.class
	function prunedRestProps(): any {
		delete $$restProps.class;
		return $$restProps;
	}
</script>

<!-- prettier-ignore -->
<div
	class="range-slider {classesBase}"
	data-testid="range-slider"
>

	<!-- Slot: Default (label) -->
	{#if $$slots.default}<label class="range-slider-label {cBaseLabel}" for={id}><slot /></label>{/if}

	<!-- Content -->
	<div class="range-content {cBaseContent}">
			
		<!-- Input -->
		<input
			type="range"
			{id}
			{name}
			class="range-slider-input {classesInput}"
			list="tickmarks-{id}"
			aria-label={label}
			{min}
			{max}
			{step}
			bind:value
			on:click
			on:change
			on:blur
			{...prunedRestProps()}
		/>

		<!-- Tickmarks -->
		{#if ticked && tickmarks && tickmarks.length}
		<datalist id="tickmarks-{id}" class="range-slider-ticks">
			{#each tickmarks as tm}
			<option value={tm} label={tm} />
			{/each}
		</datalist>
		{/if}

	</div>

	<!-- Slot: Trail -->
	{#if $$slots.trail}<div class="range-slider-trail"><slot name="trail" /></div>{/if}
	
</div>
