<script lang="ts">
	// Slots:
	/** @slot trail - A label slot directly below the range slider. */

	import { afterUpdate, tick } from 'svelte';

	// Types
	import type { CssClasses } from '$lib';

	// Props
	/**
	 * Required. Set a unique name for the input.
	 * @type {string}
	 */
	export let name: string;
	/**
	 * Provide a unique input id. Auto-generated by default
	 * @type {string}
	 */
	export let id: string = String(Math.random());
	/** Set the input value. */
	export let value = 0;
	/** Set the input minimum range. */
	export let min = 0;
	/** Set the input maximum range. */
	export let max = 100;
	/** Set the input step offset. */
	export let step = 1;
	/** Enables tick marks. See browser support below. */
	export let ticked = false;

	// Props (styles)
	/** Provide classes to set the input accent color. */
	export let accent: CssClasses = 'accent-surface-900 dark:accent-surface-50';

	// Props (a11y)
	/** A semantic ARIA label. */
	export let label = '';

	// Base Styles
	const cBase = 'space-y-2';
	const cBaseLabel = '';
	const cBaseContent = 'flex justify-center py-2';
	const cBaseInput = 'w-full h-2';

	// Local
	let tickmarks: any[];

	// Tickmarks - generate datalist options based on min/max values
	function setTicks(): void {
		if (ticked == false) return;
		tickmarks = Array.from({ length: max - min + 1 }, (_, i) => i + min);
	}

	// Lifecycle
	if (ticked) setTicks();
	afterUpdate(() => {
		setTicks();
	});

	// Reactive Classes
	$: classesBase = `${cBase} ${$$props.class ?? ''}`;
	$: classesInput = `${cBaseInput} ${accent}`;

	// Prune $$restProps to avoid overwriting $$props.class
	function prunedRestProps(): any {
		delete $$restProps.class;
		return $$restProps;
	}
</script>

<div class="range-slider {classesBase}" data-testid="range-slider">
	<!-- Slot: Default -->
	{#if $$slots.default}<label class="range-slider-label {cBaseLabel}" for={id}><slot /></label>{/if}

	<!-- Content -->
	<div class="range-content {cBaseContent}">
		<!-- Input -->
		<input
			type="range"
			{id}
			{name}
			class="range-slider-input {classesInput}"
			list="tickmarks-{id}"
			aria-label={label}
			{min}
			{max}
			{step}
			bind:value
			on:click
			on:change
			on:blur
			{...prunedRestProps()}
		/>

		<!-- Tickmarks -->
		{#if ticked && tickmarks && tickmarks.length}
			<datalist id="tickmarks-{id}" class="range-slider-ticks">
				{#each tickmarks as tm}
					<option value={tm} label={tm} />
				{/each}
			</datalist>
		{/if}
	</div>

	<!-- Slot: Trail -->
	{#if $$slots.trail}<div class="range-slider-trail"><slot name="trail" /></div>{/if}
</div>
