packages:
  - packages/*
  - playgrounds/*
  - sites/*

catalog:
  '@astrojs/check': 0.9.6
  '@astrojs/mdx': 4.3.13
  '@astrojs/partytown': 2.1.4
  '@astrojs/react': 4.4.2
  '@astrojs/sitemap': 3.6.1
  '@astrojs/svelte': 7.2.5
  '@astrojs/vercel': 9.0.3
  '@changesets/cli': 2.29.8
  '@clack/prompts': 0.11.0
  '@faker-js/faker': 10.2.0
  '@floating-ui/dom': 1.7.4
  '@internationalized/date': 3.10.1
  '@lucide/svelte': 0.562.0
  '@playwright/test': 1.57.0
  '@prettier/plugin-oxc': 0.1.3
  '@resvg/resvg-js': 2.6.2
  '@shikijs/core': 3.21.0
  '@shikijs/engine-javascript': 3.21.0
  '@shikijs/langs': 3.21.0
  '@shikijs/themes': 3.21.0
  '@shikijs/transformers': 3.21.0
  '@shikijs/types': 3.21.0
  '@stackblitz/sdk': 1.11.0
  '@sveltejs/adapter-auto': 7.0.0
  '@sveltejs/adapter-vercel': 6.3.0
  '@sveltejs/kit': 2.49.5
  '@sveltejs/package': 2.5.7
  '@sveltejs/vite-plugin-svelte': 6.2.4
  '@svitejs/changesets-changelog-github-compact': 1.2.0
  '@tailwindcss/forms': 0.5.11
  '@tailwindcss/vite': 4.1.18
  '@tanstack/react-router': 1.147.3
  '@tanstack/react-start': 1.149.0
  '@tanstack/router-cli': 1.149.0
  '@trivago/prettier-plugin-sort-imports': 6.0.2
  '@types/chroma-js': 3.1.2
  '@types/estree': 1.0.8
  '@types/html-escaper': 3.0.4
  '@types/mdast': 4.0.4
  '@types/node': 24.10.7
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  '@types/semver': 7.7.1
  '@vitejs/plugin-react': 5.1.2
  '@vitest/browser-playwright': 4.0.16
  '@zag-js/accordion': 1.32.0
  '@zag-js/avatar': 1.32.0
  '@zag-js/carousel': 1.32.0
  '@zag-js/collapsible': 1.32.0
  '@zag-js/collection': 1.32.0
  '@zag-js/combobox': 1.32.0
  '@zag-js/date-picker': 1.32.0
  '@zag-js/dialog': 1.32.0
  '@zag-js/file-upload': 1.32.0
  '@zag-js/floating-panel': 1.32.0
  '@zag-js/listbox': 1.32.0
  '@zag-js/menu': 1.32.0
  '@zag-js/pagination': 1.32.0
  '@zag-js/popover': 1.32.0
  '@zag-js/progress': 1.32.0
  '@zag-js/radio-group': 1.32.0
  '@zag-js/rating-group': 1.32.0
  '@zag-js/react': 1.32.0
  '@zag-js/slider': 1.32.0
  '@zag-js/steps': 1.32.0
  '@zag-js/svelte': 1.32.0
  '@zag-js/switch': 1.32.0
  '@zag-js/tabs': 1.32.0
  '@zag-js/tags-input': 1.32.0
  '@zag-js/toast': 1.32.0
  '@zag-js/toggle-group': 1.32.0
  '@zag-js/tooltip': 1.32.0
  '@zag-js/tree-view': 1.32.0
  astro: 5.16.8
  astro-auto-import: 0.5.1
  astro-pagefind: 1.8.5
  astro-seo: 0.8.4
  chroma-js: 3.2.0
  clean-package: 2.2.0
  colorette: 2.0.20
  commander: 14.0.2
  cross-env: 10.1.0
  detect-indent: 7.0.2
  fuse.js: 7.1.0
  html-escaper: 3.0.3
  latest-version: 9.0.0
  lucide-react: 0.562.0
  magic-string: 0.30.21
  mdast-util-from-markdown: 2.0.2
  mdast-util-gfm: 3.1.0
  mdast-util-mdx: 3.0.0
  mdast-util-to-markdown: 2.1.2
  micromark-extension-mdxjs: 3.0.0
  nanoid: 5.1.6
  node-html-parser: 7.0.2
  octokit: 5.0.5
  oxc-resolver: 11.16.2
  oxlint: 1.38.0
  oxlint-tsgolint: 0.11.0
  package-manager-detector: 1.6.0
  playwright: 1.57.0
  postcss: 8.5.6
  prettier: 3.7.4
  prettier-plugin-astro: 0.14.1
  prettier-plugin-svelte: 3.4.1
  react: 19.2.3
  react-dom: 19.2.3
  satori: 0.18.3
  semver: 7.7.3
  sharp: 0.34.5
  shiki: 3.21.0
  svelte: 5.46.1
  svelte-check: 4.3.5
  tailwindcss: 4.1.18
  tinyglobby: 0.2.15
  ts-morph: 27.0.2
  tsdown: 0.19.0
  type-fest: 5.3.1
  typescript: 5.9.3
  unist-util-visit: 5.0.0
  vite: 7.3.1
  vite-plugin-transform-lucide-imports: 0.3.0
  vitest: 4.0.16
  vitest-browser-react: 2.0.2
  vitest-browser-svelte: 2.0.1
  zimmerframe: 1.1.4

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@zag-js/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

savePrefix: ''
