packages:
  - packages/*
  - sites/*
  - playgrounds/*

catalog:
  '@zag-js/svelte': ^1.18.3
  '@zag-js/react': ^1.18.3
  '@zag-js/accordion': ^1.18.3
  '@zag-js/avatar': ^1.18.3
  '@zag-js/combobox': ^1.18.3
  '@zag-js/dialog': ^1.18.3
  '@zag-js/file-upload': ^1.18.3
  '@zag-js/pagination': ^1.18.3
  '@zag-js/popover': ^1.18.3
  '@zag-js/progress': ^1.18.3
  '@zag-js/radio-group': ^1.18.3
  '@zag-js/rating-group': ^1.18.3
  '@zag-js/slider': ^1.18.3
  '@zag-js/switch': ^1.18.3
  '@zag-js/tabs': ^1.18.3
  '@zag-js/tags-input': ^1.18.3
  '@zag-js/toast': ^1.18.3
  '@zag-js/tooltip': ^1.18.3
  typescript: ^5.8.3
  svelte: ^5.36.1
  tailwindcss: ^4.1.11

define: ^1.7.0
