// import type { PresetTheme } from './index.js';

const pine = {
	name: 'pine',
	properties: {
		'--space-scale-factor': '1.25',
		'--type-scale-factor': '1.0',
		'--type-scale-1': 'calc(0.75rem * var(--type-scale-factor))',
		'--type-scale-2': 'calc(0.875rem * var(--type-scale-factor))',
		'--type-scale-3': 'calc(1rem * var(--type-scale-factor))',
		'--type-scale-4': 'calc(1.125rem * var(--type-scale-factor))',
		'--type-scale-5': 'calc(1.25rem * var(--type-scale-factor))',
		'--type-scale-6': 'calc(1.5rem * var(--type-scale-factor))',
		'--type-scale-7': 'calc(1.875rem * var(--type-scale-factor))',
		'--type-scale-8': 'calc(2.25rem * var(--type-scale-factor))',
		'--type-scale-9': 'calc(3rem * var(--type-scale-factor))',
		'--type-scale-10': 'calc(3.75rem * var(--type-scale-factor))',
		'--type-scale-11': 'calc(4.5rem * var(--type-scale-factor))',
		'--type-scale-12': 'calc(6rem * var(--type-scale-factor))',
		'--type-scale-13': 'calc(8rem * var(--type-scale-factor))',
		'--base-font-color': 'var(--color-surface-950)',
		'--base-font-color-dark': 'var(--color-surface-50)',
		'--base-font-family': 'system-ui',
		'--base-font-size': '18px',
		'--base-line-height': '28px',
		'--base-font-weight': 'normal',
		'--base-font-style': 'normal',
		'--base-letter-spacing': '0em',
		'--heading-font-color': 'var(--color-primary-800)',
		'--heading-font-color-dark': 'var(--color-primary-300)',
		'--heading-font-family': 'Avenir, Montserrat, Corbel, URW Gothic, source-sans-pro, sans-serif',
		'--heading-font-size': '18px',
		'--heading-line-height': '28px',
		'--heading-font-weight': 'bold',
		'--heading-font-style': 'normal',
		'--heading-letter-spacing': 'inherit',
		'--anchor-font-color': 'var(--color-secondary-500)',
		'--anchor-font-color-dark': 'var(--color-secondary-100)',
		'--anchor-font-family': 'inherit',
		'--anchor-font-size': 'inherit',
		'--anchor-line-height': 'inherit',
		'--anchor-font-weight': 'normal',
		'--anchor-font-style': 'normal',
		'--anchor-letter-spacing': 'inherit',
		'--anchor-text-decoration': 'none',
		'--anchor-text-decoration-hover': 'underline',
		'--anchor-text-decoration-active': 'none',
		'--anchor-text-decoration-focus': 'none',
		'--body-background-color': 'var(--color-surface-50)',
		'--body-background-color-dark': 'var(--color-surface-950)',
		'--radii-default': '2px',
		'--radii-container': '2px',
		'--border-width-default': '1px',
		'--ring-width-default': '1px',
		'--outline-width-default': '1px',
		'--divide-width-default': '1px',
		'--color-primary-50': '251 232 208',
		'--color-primary-100': '233 211 181',
		'--color-primary-200': '215 191 154',
		'--color-primary-300': '197 170 128',
		'--color-primary-400': '179 150 101',
		'--color-primary-500': '161 129 74',
		'--color-primary-600': '144 116 66',
		'--color-primary-700': '126 103 58',
		'--color-primary-800': '109 89 49',
		'--color-primary-900': '91 76 41',
		'--color-primary-950': '74 63 33',
		'--color-primary-contrast-dark': '0 0 0',
		'--color-primary-contrast-light': '255 255 255',
		'--color-primary-contrast-50': 'var(--color-primary-contrast-dark)',
		'--color-primary-contrast-100': 'var(--color-primary-contrast-dark)',
		'--color-primary-contrast-200': 'var(--color-primary-contrast-dark)',
		'--color-primary-contrast-300': 'var(--color-primary-contrast-dark)',
		'--color-primary-contrast-400': 'var(--color-primary-contrast-dark)',
		'--color-primary-contrast-500': 'var(--color-primary-contrast-light)',
		'--color-primary-contrast-600': 'var(--color-primary-contrast-light)',
		'--color-primary-contrast-700': 'var(--color-primary-contrast-light)',
		'--color-primary-contrast-800': 'var(--color-primary-contrast-light)',
		'--color-primary-contrast-900': 'var(--color-primary-contrast-light)',
		'--color-primary-contrast-950': 'var(--color-primary-contrast-light)',
		'--color-secondary-50': '232 140 198',
		'--color-secondary-100': '203 116 170',
		'--color-secondary-200': '174 92 143',
		'--color-secondary-300': '144 69 115',
		'--color-secondary-400': '115 45 88',
		'--color-secondary-500': '86 21 60',
		'--color-secondary-600': '82 21 58',
		'--color-secondary-700': '78 21 55',
		'--color-secondary-800': '73 22 53',
		'--color-secondary-900': '69 22 50',
		'--color-secondary-950': '65 22 48',
		'--color-secondary-contrast-dark': '0 0 0',
		'--color-secondary-contrast-light': '255 255 255',
		'--color-secondary-contrast-50': 'var(--color-secondary-contrast-dark)',
		'--color-secondary-contrast-100': 'var(--color-secondary-contrast-dark)',
		'--color-secondary-contrast-200': 'var(--color-secondary-contrast-dark)',
		'--color-secondary-contrast-300': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-400': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-500': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-600': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-700': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-800': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-900': 'var(--color-secondary-contrast-light)',
		'--color-secondary-contrast-950': 'var(--color-secondary-contrast-light)',
		'--color-tertiary-50': '237 237 227',
		'--color-tertiary-100': '217 216 206',
		'--color-tertiary-200': '196 196 184',
		'--color-tertiary-300': '176 175 163',
		'--color-tertiary-400': '155 155 141',
		'--color-tertiary-500': '135 134 120',
		'--color-tertiary-600': '119 118 106',
		'--color-tertiary-700': '103 102 91',
		'--color-tertiary-800': '86 85 77',
		'--color-tertiary-900': '70 69 62',
		'--color-tertiary-950': '54 53 48',
		'--color-tertiary-contrast-dark': '0 0 0',
		'--color-tertiary-contrast-light': '255 255 255',
		'--color-tertiary-contrast-50': 'var(--color-tertiary-contrast-dark)',
		'--color-tertiary-contrast-100': 'var(--color-tertiary-contrast-dark)',
		'--color-tertiary-contrast-200': 'var(--color-tertiary-contrast-dark)',
		'--color-tertiary-contrast-300': 'var(--color-tertiary-contrast-dark)',
		'--color-tertiary-contrast-400': 'var(--color-tertiary-contrast-dark)',
		'--color-tertiary-contrast-500': 'var(--color-tertiary-contrast-light)',
		'--color-tertiary-contrast-600': 'var(--color-tertiary-contrast-light)',
		'--color-tertiary-contrast-700': 'var(--color-tertiary-contrast-light)',
		'--color-tertiary-contrast-800': 'var(--color-tertiary-contrast-light)',
		'--color-tertiary-contrast-900': 'var(--color-tertiary-contrast-light)',
		'--color-tertiary-contrast-950': 'var(--color-tertiary-contrast-light)',
		'--color-success-50': '110 176 180',
		'--color-success-100': '88 160 161',
		'--color-success-200': '67 144 142',
		'--color-success-300': '45 127 122',
		'--color-success-400': '24 111 103',
		'--color-success-500': '2 95 84',
		'--color-success-600': '7 87 78',
		'--color-success-700': '12 79 72',
		'--color-success-800': '16 70 67',
		'--color-success-900': '21 62 61',
		'--color-success-950': '26 54 55',
		'--color-success-contrast-dark': '0 0 0',
		'--color-success-contrast-light': '255 255 255',
		'--color-success-contrast-50': 'var(--color-success-contrast-dark)',
		'--color-success-contrast-100': 'var(--color-success-contrast-dark)',
		'--color-success-contrast-200': 'var(--color-success-contrast-dark)',
		'--color-success-contrast-300': 'var(--color-success-contrast-light)',
		'--color-success-contrast-400': 'var(--color-success-contrast-light)',
		'--color-success-contrast-500': 'var(--color-success-contrast-light)',
		'--color-success-contrast-600': 'var(--color-success-contrast-light)',
		'--color-success-contrast-700': 'var(--color-success-contrast-light)',
		'--color-success-contrast-800': 'var(--color-success-contrast-light)',
		'--color-success-contrast-900': 'var(--color-success-contrast-light)',
		'--color-success-contrast-950': 'var(--color-success-contrast-light)',
		'--color-warning-50': '255 235 204',
		'--color-warning-100': '253 223 177',
		'--color-warning-200': '251 211 149',
		'--color-warning-300': '248 200 122',
		'--color-warning-400': '246 188 94',
		'--color-warning-500': '244 176 67',
		'--color-warning-600': '209 153 62',
		'--color-warning-700': '175 130 57',
		'--color-warning-800': '140 106 52',
		'--color-warning-900': '106 83 47',
		'--color-warning-950': '71 60 42',
		'--color-warning-contrast-dark': 'var(--color-warning-950)',
		'--color-warning-contrast-light': 'var(--color-warning-50)',
		'--color-warning-contrast-50': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-100': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-200': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-300': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-400': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-500': 'var(--color-warning-contrast-dark)',
		'--color-warning-contrast-600': 'var(--color-warning-contrast-light)',
		'--color-warning-contrast-700': 'var(--color-warning-contrast-light)',
		'--color-warning-contrast-800': 'var(--color-warning-contrast-light)',
		'--color-warning-contrast-900': 'var(--color-warning-contrast-light)',
		'--color-warning-contrast-950': 'var(--color-warning-contrast-light)',
		'--color-error-50': '255 216 209',
		'--color-error-100': '248 196 186',
		'--color-error-200': '241 175 163',
		'--color-error-300': '235 155 141',
		'--color-error-400': '228 134 118',
		'--color-error-500': '221 114 95',
		'--color-error-600': '191 99 83',
		'--color-error-700': '160 84 70',
		'--color-error-800': '130 68 58',
		'--color-error-900': '99 53 45',
		'--color-error-950': '69 38 33',
		'--color-error-contrast-dark': 'var(--color-error-950)',
		'--color-error-contrast-light': 'var(--color-error-50)',
		'--color-error-contrast-50': 'var(--color-error-contrast-dark)',
		'--color-error-contrast-100': 'var(--color-error-contrast-dark)',
		'--color-error-contrast-200': 'var(--color-error-contrast-dark)',
		'--color-error-contrast-300': 'var(--color-error-contrast-dark)',
		'--color-error-contrast-400': 'var(--color-error-contrast-dark)',
		'--color-error-contrast-500': 'var(--color-error-contrast-light)',
		'--color-error-contrast-600': 'var(--color-error-contrast-light)',
		'--color-error-contrast-700': 'var(--color-error-contrast-light)',
		'--color-error-contrast-800': 'var(--color-error-contrast-light)',
		'--color-error-contrast-900': 'var(--color-error-contrast-light)',
		'--color-error-contrast-950': 'var(--color-error-contrast-light)',
		'--color-surface-50': '216 219 210',
		'--color-surface-100': '195 200 187',
		'--color-surface-200': '173 181 164',
		'--color-surface-300': '152 163 140',
		'--color-surface-400': '130 144 117',
		'--color-surface-500': '109 125 94',
		'--color-surface-600': '93 107 80',
		'--color-surface-700': '77 89 66',
		'--color-surface-800': '61 70 52',
		'--color-surface-900': '45 52 38',
		'--color-surface-950': '29 34 24',
		'--color-surface-contrast-dark': 'var(--color-surface-950)',
		'--color-surface-contrast-light': 'var(--color-surface-50)',
		'--color-surface-contrast-50': 'var(--color-surface-contrast-dark)',
		'--color-surface-contrast-100': 'var(--color-surface-contrast-dark)',
		'--color-surface-contrast-200': 'var(--color-surface-contrast-dark)',
		'--color-surface-contrast-300': 'var(--color-surface-contrast-dark)',
		'--color-surface-contrast-400': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-500': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-600': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-700': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-800': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-900': 'var(--color-surface-contrast-light)',
		'--color-surface-contrast-950': 'var(--color-surface-contrast-light)'
	}
}; // satisfies PresetTheme;

export default pine;
