name: ðŸž Bug
description: Report an issue or bug
labels: [bug]
type: Bug
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: How do you think should it behave.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Describe how to reproduce the issue.
      placeholder: |
        1. Using this component...
        2. With these properties...
        3. Click '...'
        4. See error...
    validations:
      required: false
  - type: input
    id: reproduction
    attributes:
      label: Stackblitz or Reproduction URL
      description: To create a Stackblitz reproduction, view our docs, find a relevant example, then tap the Stackblitz button at the top-right corner. Modify as needed, then share a link to this here.
    validations:
      require: true
  - type: textarea
    attributes:
      label: Environment Information
      description: Relevant information about your environment. Use `npx envinfo --system --npmPackages "@skeletonlabs/*" --binaries --browsers` to get this information.
      placeholder: |
        System:
          OS: Windows 11 X.X.XXXXX
          CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
          Memory: 4.72 GB / 15.78 GB
        Binaries:
          Node: XX.XX.X - C:\Program Files\nodejs\node.EXE
          Yarn: X.XX.XX - ~\AppData\Roaming\npm\yarn.CMD
          npm: XX.X.X - C:\Program Files\nodejs\npm.CMD
          pnpm: X.X.X - ~\AppData\Local\pnpm\pnpm.CMD
        Browsers:
          Edge: Chromium (XXX.X.XXXX.XX)
          Internet Explorer: XX.X.XXXXX.XXXX
        npmPackages:
          @skeletonlabs/skeleton: ^X.X.X => X.X.X
          @skeletonlabs/skeleton-svelte: ^X.X.X => X.X.X
  - type: textarea
    attributes:
      label: More Information
      description: |
        Provide additional information, videos, gifs, or screenshots here.
    validations:
      required: false
