name: 📗 Report Docs Issue
description: Use this to report a typo or incorrect information.
labels: [documentation]
type: Task
body:
  - type: input
    id: link
    attributes:
      label: Link to the Page
  - type: textarea
    id: quote
    attributes:
      label: Describe this issue. Screenshots are encouraged.
