export { SegmentedControl } from './modules/anatomy.js';
export { useSegmentedControl } from './modules/provider.js';
export type { SegmentedControlRootProps } from './anatomy/root.jsx';
export type { SegmentedControlRootContextProps } from './anatomy/root-context.jsx';
export type { SegmentedControlRootProviderProps } from './anatomy/root-provider.jsx';
export type { SegmentedControlLabelProps } from './anatomy/label.jsx';
export type { SegmentedControlControlProps } from './anatomy/control.jsx';
export type { SegmentedControlIndicatorProps } from './anatomy/indicator.jsx';
export type { SegmentedControlItemProps } from './anatomy/item.jsx';
export type { SegmentedControlItemTextProps } from './anatomy/item-text.jsx';
export type { SegmentedControlItemHiddenInputProps } from './anatomy/item-hidden-input.jsx';
