/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsTreeViewIndexRouteImport } from './routes/components/tree-view/index'
import { Route as ComponentsTooltipIndexRouteImport } from './routes/components/tooltip/index'
import { Route as ComponentsToggleGroupIndexRouteImport } from './routes/components/toggle-group/index'
import { Route as ComponentsToastIndexRouteImport } from './routes/components/toast/index'
import { Route as ComponentsTagsInputIndexRouteImport } from './routes/components/tags-input/index'
import { Route as ComponentsTabsIndexRouteImport } from './routes/components/tabs/index'
import { Route as ComponentsSwitchIndexRouteImport } from './routes/components/switch/index'
import { Route as ComponentsSliderIndexRouteImport } from './routes/components/slider/index'
import { Route as ComponentsSegmentedControlIndexRouteImport } from './routes/components/segmented-control/index'
import { Route as ComponentsRatingGroupIndexRouteImport } from './routes/components/rating-group/index'
import { Route as ComponentsProgressLinearIndexRouteImport } from './routes/components/progress-linear/index'
import { Route as ComponentsProgressCircularIndexRouteImport } from './routes/components/progress-circular/index'
import { Route as ComponentsPopoverIndexRouteImport } from './routes/components/popover/index'
import { Route as ComponentsPaginationIndexRouteImport } from './routes/components/pagination/index'
import { Route as ComponentsNavigationIndexRouteImport } from './routes/components/navigation/index'
import { Route as ComponentsMenuIndexRouteImport } from './routes/components/menu/index'
import { Route as ComponentsListboxIndexRouteImport } from './routes/components/listbox/index'
import { Route as ComponentsFileUploadIndexRouteImport } from './routes/components/file-upload/index'
import { Route as ComponentsDialogIndexRouteImport } from './routes/components/dialog/index'
import { Route as ComponentsDatePickerIndexRouteImport } from './routes/components/date-picker/index'
import { Route as ComponentsComboboxIndexRouteImport } from './routes/components/combobox/index'
import { Route as ComponentsCollapsibleIndexRouteImport } from './routes/components/collapsible/index'
import { Route as ComponentsAvatarIndexRouteImport } from './routes/components/avatar/index'
import { Route as ComponentsAppBarIndexRouteImport } from './routes/components/app-bar/index'
import { Route as ComponentsAccordionIndexRouteImport } from './routes/components/accordion/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTreeViewIndexRoute = ComponentsTreeViewIndexRouteImport.update({
  id: '/components/tree-view/',
  path: '/components/tree-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipIndexRoute = ComponentsTooltipIndexRouteImport.update({
  id: '/components/tooltip/',
  path: '/components/tooltip/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleGroupIndexRoute =
  ComponentsToggleGroupIndexRouteImport.update({
    id: '/components/toggle-group/',
    path: '/components/toggle-group/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsToastIndexRoute = ComponentsToastIndexRouteImport.update({
  id: '/components/toast/',
  path: '/components/toast/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTagsInputIndexRoute =
  ComponentsTagsInputIndexRouteImport.update({
    id: '/components/tags-input/',
    path: '/components/tags-input/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsTabsIndexRoute = ComponentsTabsIndexRouteImport.update({
  id: '/components/tabs/',
  path: '/components/tabs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchIndexRoute = ComponentsSwitchIndexRouteImport.update({
  id: '/components/switch/',
  path: '/components/switch/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderIndexRoute = ComponentsSliderIndexRouteImport.update({
  id: '/components/slider/',
  path: '/components/slider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSegmentedControlIndexRoute =
  ComponentsSegmentedControlIndexRouteImport.update({
    id: '/components/segmented-control/',
    path: '/components/segmented-control/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsRatingGroupIndexRoute =
  ComponentsRatingGroupIndexRouteImport.update({
    id: '/components/rating-group/',
    path: '/components/rating-group/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsProgressLinearIndexRoute =
  ComponentsProgressLinearIndexRouteImport.update({
    id: '/components/progress-linear/',
    path: '/components/progress-linear/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsProgressCircularIndexRoute =
  ComponentsProgressCircularIndexRouteImport.update({
    id: '/components/progress-circular/',
    path: '/components/progress-circular/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsPopoverIndexRoute = ComponentsPopoverIndexRouteImport.update({
  id: '/components/popover/',
  path: '/components/popover/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPaginationIndexRoute =
  ComponentsPaginationIndexRouteImport.update({
    id: '/components/pagination/',
    path: '/components/pagination/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsNavigationIndexRoute =
  ComponentsNavigationIndexRouteImport.update({
    id: '/components/navigation/',
    path: '/components/navigation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsMenuIndexRoute = ComponentsMenuIndexRouteImport.update({
  id: '/components/menu/',
  path: '/components/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsListboxIndexRoute = ComponentsListboxIndexRouteImport.update({
  id: '/components/listbox/',
  path: '/components/listbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFileUploadIndexRoute =
  ComponentsFileUploadIndexRouteImport.update({
    id: '/components/file-upload/',
    path: '/components/file-upload/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsDialogIndexRoute = ComponentsDialogIndexRouteImport.update({
  id: '/components/dialog/',
  path: '/components/dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerIndexRoute =
  ComponentsDatePickerIndexRouteImport.update({
    id: '/components/date-picker/',
    path: '/components/date-picker/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsComboboxIndexRoute = ComponentsComboboxIndexRouteImport.update({
  id: '/components/combobox/',
  path: '/components/combobox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCollapsibleIndexRoute =
  ComponentsCollapsibleIndexRouteImport.update({
    id: '/components/collapsible/',
    path: '/components/collapsible/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsAvatarIndexRoute = ComponentsAvatarIndexRouteImport.update({
  id: '/components/avatar/',
  path: '/components/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAppBarIndexRoute = ComponentsAppBarIndexRouteImport.update({
  id: '/components/app-bar/',
  path: '/components/app-bar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionIndexRoute =
  ComponentsAccordionIndexRouteImport.update({
    id: '/components/accordion/',
    path: '/components/accordion/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionIndexRoute
  '/components/app-bar': typeof ComponentsAppBarIndexRoute
  '/components/avatar': typeof ComponentsAvatarIndexRoute
  '/components/collapsible': typeof ComponentsCollapsibleIndexRoute
  '/components/combobox': typeof ComponentsComboboxIndexRoute
  '/components/date-picker': typeof ComponentsDatePickerIndexRoute
  '/components/dialog': typeof ComponentsDialogIndexRoute
  '/components/file-upload': typeof ComponentsFileUploadIndexRoute
  '/components/listbox': typeof ComponentsListboxIndexRoute
  '/components/menu': typeof ComponentsMenuIndexRoute
  '/components/navigation': typeof ComponentsNavigationIndexRoute
  '/components/pagination': typeof ComponentsPaginationIndexRoute
  '/components/popover': typeof ComponentsPopoverIndexRoute
  '/components/progress-circular': typeof ComponentsProgressCircularIndexRoute
  '/components/progress-linear': typeof ComponentsProgressLinearIndexRoute
  '/components/rating-group': typeof ComponentsRatingGroupIndexRoute
  '/components/segmented-control': typeof ComponentsSegmentedControlIndexRoute
  '/components/slider': typeof ComponentsSliderIndexRoute
  '/components/switch': typeof ComponentsSwitchIndexRoute
  '/components/tabs': typeof ComponentsTabsIndexRoute
  '/components/tags-input': typeof ComponentsTagsInputIndexRoute
  '/components/toast': typeof ComponentsToastIndexRoute
  '/components/toggle-group': typeof ComponentsToggleGroupIndexRoute
  '/components/tooltip': typeof ComponentsTooltipIndexRoute
  '/components/tree-view': typeof ComponentsTreeViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionIndexRoute
  '/components/app-bar': typeof ComponentsAppBarIndexRoute
  '/components/avatar': typeof ComponentsAvatarIndexRoute
  '/components/collapsible': typeof ComponentsCollapsibleIndexRoute
  '/components/combobox': typeof ComponentsComboboxIndexRoute
  '/components/date-picker': typeof ComponentsDatePickerIndexRoute
  '/components/dialog': typeof ComponentsDialogIndexRoute
  '/components/file-upload': typeof ComponentsFileUploadIndexRoute
  '/components/listbox': typeof ComponentsListboxIndexRoute
  '/components/menu': typeof ComponentsMenuIndexRoute
  '/components/navigation': typeof ComponentsNavigationIndexRoute
  '/components/pagination': typeof ComponentsPaginationIndexRoute
  '/components/popover': typeof ComponentsPopoverIndexRoute
  '/components/progress-circular': typeof ComponentsProgressCircularIndexRoute
  '/components/progress-linear': typeof ComponentsProgressLinearIndexRoute
  '/components/rating-group': typeof ComponentsRatingGroupIndexRoute
  '/components/segmented-control': typeof ComponentsSegmentedControlIndexRoute
  '/components/slider': typeof ComponentsSliderIndexRoute
  '/components/switch': typeof ComponentsSwitchIndexRoute
  '/components/tabs': typeof ComponentsTabsIndexRoute
  '/components/tags-input': typeof ComponentsTagsInputIndexRoute
  '/components/toast': typeof ComponentsToastIndexRoute
  '/components/toggle-group': typeof ComponentsToggleGroupIndexRoute
  '/components/tooltip': typeof ComponentsTooltipIndexRoute
  '/components/tree-view': typeof ComponentsTreeViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/accordion/': typeof ComponentsAccordionIndexRoute
  '/components/app-bar/': typeof ComponentsAppBarIndexRoute
  '/components/avatar/': typeof ComponentsAvatarIndexRoute
  '/components/collapsible/': typeof ComponentsCollapsibleIndexRoute
  '/components/combobox/': typeof ComponentsComboboxIndexRoute
  '/components/date-picker/': typeof ComponentsDatePickerIndexRoute
  '/components/dialog/': typeof ComponentsDialogIndexRoute
  '/components/file-upload/': typeof ComponentsFileUploadIndexRoute
  '/components/listbox/': typeof ComponentsListboxIndexRoute
  '/components/menu/': typeof ComponentsMenuIndexRoute
  '/components/navigation/': typeof ComponentsNavigationIndexRoute
  '/components/pagination/': typeof ComponentsPaginationIndexRoute
  '/components/popover/': typeof ComponentsPopoverIndexRoute
  '/components/progress-circular/': typeof ComponentsProgressCircularIndexRoute
  '/components/progress-linear/': typeof ComponentsProgressLinearIndexRoute
  '/components/rating-group/': typeof ComponentsRatingGroupIndexRoute
  '/components/segmented-control/': typeof ComponentsSegmentedControlIndexRoute
  '/components/slider/': typeof ComponentsSliderIndexRoute
  '/components/switch/': typeof ComponentsSwitchIndexRoute
  '/components/tabs/': typeof ComponentsTabsIndexRoute
  '/components/tags-input/': typeof ComponentsTagsInputIndexRoute
  '/components/toast/': typeof ComponentsToastIndexRoute
  '/components/toggle-group/': typeof ComponentsToggleGroupIndexRoute
  '/components/tooltip/': typeof ComponentsTooltipIndexRoute
  '/components/tree-view/': typeof ComponentsTreeViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/accordion'
    | '/components/app-bar'
    | '/components/avatar'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/file-upload'
    | '/components/listbox'
    | '/components/menu'
    | '/components/navigation'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress-circular'
    | '/components/progress-linear'
    | '/components/rating-group'
    | '/components/segmented-control'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tags-input'
    | '/components/toast'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/components/tree-view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/accordion'
    | '/components/app-bar'
    | '/components/avatar'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/file-upload'
    | '/components/listbox'
    | '/components/menu'
    | '/components/navigation'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress-circular'
    | '/components/progress-linear'
    | '/components/rating-group'
    | '/components/segmented-control'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tags-input'
    | '/components/toast'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/components/tree-view'
  id:
    | '__root__'
    | '/'
    | '/components/accordion/'
    | '/components/app-bar/'
    | '/components/avatar/'
    | '/components/collapsible/'
    | '/components/combobox/'
    | '/components/date-picker/'
    | '/components/dialog/'
    | '/components/file-upload/'
    | '/components/listbox/'
    | '/components/menu/'
    | '/components/navigation/'
    | '/components/pagination/'
    | '/components/popover/'
    | '/components/progress-circular/'
    | '/components/progress-linear/'
    | '/components/rating-group/'
    | '/components/segmented-control/'
    | '/components/slider/'
    | '/components/switch/'
    | '/components/tabs/'
    | '/components/tags-input/'
    | '/components/toast/'
    | '/components/toggle-group/'
    | '/components/tooltip/'
    | '/components/tree-view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsAccordionIndexRoute: typeof ComponentsAccordionIndexRoute
  ComponentsAppBarIndexRoute: typeof ComponentsAppBarIndexRoute
  ComponentsAvatarIndexRoute: typeof ComponentsAvatarIndexRoute
  ComponentsCollapsibleIndexRoute: typeof ComponentsCollapsibleIndexRoute
  ComponentsComboboxIndexRoute: typeof ComponentsComboboxIndexRoute
  ComponentsDatePickerIndexRoute: typeof ComponentsDatePickerIndexRoute
  ComponentsDialogIndexRoute: typeof ComponentsDialogIndexRoute
  ComponentsFileUploadIndexRoute: typeof ComponentsFileUploadIndexRoute
  ComponentsListboxIndexRoute: typeof ComponentsListboxIndexRoute
  ComponentsMenuIndexRoute: typeof ComponentsMenuIndexRoute
  ComponentsNavigationIndexRoute: typeof ComponentsNavigationIndexRoute
  ComponentsPaginationIndexRoute: typeof ComponentsPaginationIndexRoute
  ComponentsPopoverIndexRoute: typeof ComponentsPopoverIndexRoute
  ComponentsProgressCircularIndexRoute: typeof ComponentsProgressCircularIndexRoute
  ComponentsProgressLinearIndexRoute: typeof ComponentsProgressLinearIndexRoute
  ComponentsRatingGroupIndexRoute: typeof ComponentsRatingGroupIndexRoute
  ComponentsSegmentedControlIndexRoute: typeof ComponentsSegmentedControlIndexRoute
  ComponentsSliderIndexRoute: typeof ComponentsSliderIndexRoute
  ComponentsSwitchIndexRoute: typeof ComponentsSwitchIndexRoute
  ComponentsTabsIndexRoute: typeof ComponentsTabsIndexRoute
  ComponentsTagsInputIndexRoute: typeof ComponentsTagsInputIndexRoute
  ComponentsToastIndexRoute: typeof ComponentsToastIndexRoute
  ComponentsToggleGroupIndexRoute: typeof ComponentsToggleGroupIndexRoute
  ComponentsTooltipIndexRoute: typeof ComponentsTooltipIndexRoute
  ComponentsTreeViewIndexRoute: typeof ComponentsTreeViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tree-view/': {
      id: '/components/tree-view/'
      path: '/components/tree-view'
      fullPath: '/components/tree-view'
      preLoaderRoute: typeof ComponentsTreeViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip/': {
      id: '/components/tooltip/'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle-group/': {
      id: '/components/toggle-group/'
      path: '/components/toggle-group'
      fullPath: '/components/toggle-group'
      preLoaderRoute: typeof ComponentsToggleGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toast/': {
      id: '/components/toast/'
      path: '/components/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tags-input/': {
      id: '/components/tags-input/'
      path: '/components/tags-input'
      fullPath: '/components/tags-input'
      preLoaderRoute: typeof ComponentsTagsInputIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs/': {
      id: '/components/tabs/'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch/': {
      id: '/components/switch/'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider/': {
      id: '/components/slider/'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/segmented-control/': {
      id: '/components/segmented-control/'
      path: '/components/segmented-control'
      fullPath: '/components/segmented-control'
      preLoaderRoute: typeof ComponentsSegmentedControlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/rating-group/': {
      id: '/components/rating-group/'
      path: '/components/rating-group'
      fullPath: '/components/rating-group'
      preLoaderRoute: typeof ComponentsRatingGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/progress-linear/': {
      id: '/components/progress-linear/'
      path: '/components/progress-linear'
      fullPath: '/components/progress-linear'
      preLoaderRoute: typeof ComponentsProgressLinearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/progress-circular/': {
      id: '/components/progress-circular/'
      path: '/components/progress-circular'
      fullPath: '/components/progress-circular'
      preLoaderRoute: typeof ComponentsProgressCircularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/popover/': {
      id: '/components/popover/'
      path: '/components/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/pagination/': {
      id: '/components/pagination/'
      path: '/components/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/navigation/': {
      id: '/components/navigation/'
      path: '/components/navigation'
      fullPath: '/components/navigation'
      preLoaderRoute: typeof ComponentsNavigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/menu/': {
      id: '/components/menu/'
      path: '/components/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/listbox/': {
      id: '/components/listbox/'
      path: '/components/listbox'
      fullPath: '/components/listbox'
      preLoaderRoute: typeof ComponentsListboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/file-upload/': {
      id: '/components/file-upload/'
      path: '/components/file-upload'
      fullPath: '/components/file-upload'
      preLoaderRoute: typeof ComponentsFileUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dialog/': {
      id: '/components/dialog/'
      path: '/components/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker/': {
      id: '/components/date-picker/'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/combobox/': {
      id: '/components/combobox/'
      path: '/components/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/collapsible/': {
      id: '/components/collapsible/'
      path: '/components/collapsible'
      fullPath: '/components/collapsible'
      preLoaderRoute: typeof ComponentsCollapsibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/avatar/': {
      id: '/components/avatar/'
      path: '/components/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/app-bar/': {
      id: '/components/app-bar/'
      path: '/components/app-bar'
      fullPath: '/components/app-bar'
      preLoaderRoute: typeof ComponentsAppBarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion/': {
      id: '/components/accordion/'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsAccordionIndexRoute: ComponentsAccordionIndexRoute,
  ComponentsAppBarIndexRoute: ComponentsAppBarIndexRoute,
  ComponentsAvatarIndexRoute: ComponentsAvatarIndexRoute,
  ComponentsCollapsibleIndexRoute: ComponentsCollapsibleIndexRoute,
  ComponentsComboboxIndexRoute: ComponentsComboboxIndexRoute,
  ComponentsDatePickerIndexRoute: ComponentsDatePickerIndexRoute,
  ComponentsDialogIndexRoute: ComponentsDialogIndexRoute,
  ComponentsFileUploadIndexRoute: ComponentsFileUploadIndexRoute,
  ComponentsListboxIndexRoute: ComponentsListboxIndexRoute,
  ComponentsMenuIndexRoute: ComponentsMenuIndexRoute,
  ComponentsNavigationIndexRoute: ComponentsNavigationIndexRoute,
  ComponentsPaginationIndexRoute: ComponentsPaginationIndexRoute,
  ComponentsPopoverIndexRoute: ComponentsPopoverIndexRoute,
  ComponentsProgressCircularIndexRoute: ComponentsProgressCircularIndexRoute,
  ComponentsProgressLinearIndexRoute: ComponentsProgressLinearIndexRoute,
  ComponentsRatingGroupIndexRoute: ComponentsRatingGroupIndexRoute,
  ComponentsSegmentedControlIndexRoute: ComponentsSegmentedControlIndexRoute,
  ComponentsSliderIndexRoute: ComponentsSliderIndexRoute,
  ComponentsSwitchIndexRoute: ComponentsSwitchIndexRoute,
  ComponentsTabsIndexRoute: ComponentsTabsIndexRoute,
  ComponentsTagsInputIndexRoute: ComponentsTagsInputIndexRoute,
  ComponentsToastIndexRoute: ComponentsToastIndexRoute,
  ComponentsToggleGroupIndexRoute: ComponentsToggleGroupIndexRoute,
  ComponentsTooltipIndexRoute: ComponentsTooltipIndexRoute,
  ComponentsTreeViewIndexRoute: ComponentsTreeViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
