export type { TagsInputClearTriggerProps } from './anatomy/clear-trigger.jsx';
export type { TagsInputControlProps } from './anatomy/control.jsx';
export type { TagsInputHiddenInputProps } from './anatomy/hidden-input.jsx';
export type { TagsInputInputProps } from './anatomy/input.jsx';
export type { TagsInputItemProps } from './anatomy/item.jsx';
export type { TagsInputItemDeleteTriggerProps } from './anatomy/item-delete-trigger.jsx';
export type { TagsInputItemInputProps } from './anatomy/item-input.jsx';
export type { TagsInputItemPreviewProps } from './anatomy/item-preview.jsx';
export type { TagsInputItemTextProps } from './anatomy/item-text.jsx';
export type { TagsInputLabelProps } from './anatomy/label.jsx';
export type { TagsInputRootProps } from './anatomy/root.jsx';
export type { TagsInputRootContextProps } from './anatomy/root-context.jsx';
export type { TagsInputRootProviderProps } from './anatomy/root-provider.jsx';
export { TagsInput } from './modules/anatomy.js';
export { useTagsInput } from './modules/provider.js';
