export { Dialog } from './modules/anatomy';
export type { DialogRootProps } from './anatomy/root';
export type { DialogRootContextProps } from './anatomy/root-context';
export type { DialogTriggerProps } from './anatomy/trigger';
export type { DialogBackdropProps } from './anatomy/backdrop';
export type { DialogPositionerProps } from './anatomy/positioner';
export type { DialogContentProps } from './anatomy/content';
export type { DialogTitleProps } from './anatomy/title';
export type { DialogDescriptionProps } from './anatomy/description';
export type { DialogCloseTriggerProps } from './anatomy/close-trigger';
export type { DialogRootContextType as DialogRootContext } from './modules/root-context';
