<script lang="ts">
	// Slots:
	/**
	 * @slot {{}} lead - Allows for an optional leading element, such as an icon.
	 * @slot {{}} summary - Provide the interactive summary of each item.
	 * @slot {{}} content - Provide the content content of each item.
	 */
	// Events:
	// FORWARDED: do not document these, breaks the type definition
	// DISPATCHED: document directly above the definition, like props (ex: paginator)

	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';
	import { slide } from 'svelte/transition';

	// Types
	import type { CssClasses } from '$lib';

	// Props (state)
	/** Set open by default on load. */
	export let open = false;
	// Props (a11y)
	/**
	 * Provide a unique input id. Auto-generated by default
	 * @type {string}
	 */
	export let id: string = String(Math.random());

	// Classes
	const cBase = '';
	const cControl = 'text-left w-full flex items-center space-x-4';
	const cControlCaret = 'fill-token w-3 transition-transform duration-[200ms]';
	const cPanel = '';

	// Context API
	/** Set the auto-collapse mode. */
	export let autocollapse: boolean = getContext('autocollapse');
	/** The writable store that houses the auto-collapse active item UUID. */
	export let active: Writable<string | null> = getContext('active');
	/** Set the drawer animation duration. */
	export let duration: number = getContext('duration');
	// ---
	/** Provide classes to set the accordion item padding styles. */
	export let padding: CssClasses = getContext('padding');
	/** Provide classes to set the accordion item hover styles. */
	export let hover: CssClasses = getContext('hover');
	/** Provide classes to set the accordion item rounded styles. */
	export let rounded: CssClasses = getContext('rounded');
	// ---
	/** Provide arbitrary classes to the trigger button region. */
	export let regionControl: CssClasses = getContext('regionControl');
	/** Provide arbitrary classes to content panel region. */
	export let regionPanel: CssClasses = getContext('regionPanel');
	/** Provide arbitrary classes caret icon region. */
	export let regionCaret: CssClasses = getContext('regionCaret');

	// Change open behavior based on auto-collapse mode
	function setActive(): void {
		// Set item active
		if (autocollapse === true) {
			active.set(id);
			return;
		}
		// Toggle Item on click
		open = !open;
	}

	// If auto-collapse mode enabled and item is set open, set as this item active
	if (autocollapse && open) setActive();

	// Reactive State
	$: if (open && autocollapse) setActive();
	$: openState = autocollapse ? $active === id : open;
	// Reactive Classes
	$: classesBase = `${cBase} ${$$props.class ?? ''}`;
	$: classesControl = `${cControl} ${padding} ${hover} ${rounded} ${regionControl}`;
	$: classesCaretState = openState ? 'rotate-180' : '';
	$: classesControlCaret = `${cControlCaret} ${regionCaret} ${classesCaretState}`;
	$: classesPanel = `${cPanel} ${padding} ${rounded} ${regionPanel}`;
</script>

<!-- @component The Accordion child element. -->

<div class="accordion-item {classesBase}" data-testid="accordion-item">
	<!-- Control -->
	<button
		class="accordion-control {classesControl}"
		id="accordion-control-{id}"
		on:click={setActive}
		on:click
		on:keydown
		on:keyup
		on:keypress
		on:toggle
		aria-expanded={openState}
		aria-controls="accordion-panel-{id}"
	>
		<!-- Lead -->
		{#if $$slots.lead}
			<div class="accordion-lead">
				<slot name="lead" />
			</div>
		{/if}
		<!-- Summary -->
		<div class="accordion-summary flex-1">
			<slot name="summary">(summary)</slot>
		</div>
		<!-- Caret -->
		<div class="accordion-summary-caret {classesControlCaret}">
			<!-- SVG Caret -->
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
				<path
					d="M201.4 374.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 306.7 86.6 169.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"
				/>
			</svg>
		</div>
	</button>
	<!-- Panel -->
	{#if openState}
		<div
			class="accordion-panel {classesPanel}"
			id="accordion-panel-{id}"
			transition:slide|local={{ duration }}
			role="region"
			aria-hidden={!openState}
			aria-labelledby="accordion-control-{id}"
		>
			<slot name="content">(content)</slot>
		</div>
	{/if}
</div>
