#!/bin/sh
# Usage: skel my-new-app
# Auto-runs Svelte-Kit + Tailwind + Skeleton setup to make it a one liner for setting a up a fresh Skeleton app.
# Either call this script directly, or preferably drop it into a bin directory that is in your $PATH. You need jq, pnpm installed as well
# Most likely you should tweak the options depending on what you are testing.

npm init @svelte-add/kit@latest $1 -y -- --with typescript+eslint+prettier+tailwindcss --tailwindcss-typography --tailwindcss-forms
#additional options --install --tailwindcss-typography --tailwindcss-forms
cd $1/
#pnpm i @brainandbones/skeleton --save-dev //re-enable when a @dev scope comes along
cat <<EOT > tailwind.config.cjs
const typography = require('@tailwindcss/typography');
const forms = require('@tailwindcss/forms');
const skeleton = require('@brainandbones/skeleton/tailwind.cjs');

const config = {
	content: ['./src/**/*.{html,js,svelte,ts}', './node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}'],

	theme: {
		extend: {}
	},

	plugins: [forms, typography, skeleton]
};

module.exports = config;
EOT
#curl -s -o src/app.postcss https://raw.githubusercontent.com/Brain-Bones/skeleton/master/src/app.css
cat <<EOT > src/routes/+layout.svelte
<script>
	import '@brainandbones/skeleton/styles/all.css';
	import '@brainandbones/skeleton/themes/theme-skeleton.css';
	import '../app.postcss';
</script>

<slot />
EOT
