<script lang="ts">
	import CodeBlock from '$lib/utilities/CodeBlock/CodeBlock.svelte';
	import ConicGradient from '$lib/components/ConicGradient/ConicGradient.svelte';
	import DataTable from '$lib/components/Table/DataTable.svelte';

	import type { ConicColorStop } from '$lib/components/ConicGradient/types';

	// Chart Data
	let dataTailwindColors: ConicColorStop[] = [
		{ label: 'Orange', color: ['orange', 500], start: 0, end: 10 },
		{ label: 'Yellow', color: ['yellow', 500], start: 10, end: 35 },
		{ label: 'Red', color: ['red', 500], start: 35, end: 100 }
	];
	const dataColorVars: ConicColorStop[] = [
		{ label: 'Primary', color: 'rgb(var(--color-primary-500))', start: 0, end: 33 },
		{ label: 'Acccent', color: 'rgb(var(--color-warning-500))', start: 33, end: 66 },
		{ label: 'Warning', color: 'rgb(var(--color-accent-500))', start: 66, end: 100 }
	];
	const dataSpinner: ConicColorStop[] = [
		{ color: 'transparent', start: 0, end: 25 },
		{ color: 'rgba(128,128,128,0.5)', start: 75, end: 100 }
	];

	// Tables
	const tableProps: any = {
		headings: ['Prop', 'Type', 'Default', 'Required', 'Description'],
		source: [
			['data', 'arrary', '(100% grey circle)', '&check;', 'Provide a data set of color stops and labels.'],
			['legend', 'boolean', 'false', '-', 'Allows for automatic generation of a legend below the conic gradient.'],
			['spin', 'boolean', 'false', '-', 'When enabled, the conic gradient will spin.'],
			['width', 'string', 'w-full', '-', 'Provided classes to style the conic gradient width.'],
			['hover', 'string', 'hover:bg-surface-500/10', '-', 'Provided classes to style the legend hover effect.']
		]
	};
	const tableSlots: any = {
		headings: ['Name', 'Description'],
		source: [['default', 'Provide a semantic figure caption value.']]
	};
</script>

<div class="space-y-8">
	<!-- Header -->
	<header class="space-y-4">
		<h1>Conic Gradient</h1>
		<p>Create conic gradient visualizations for pie charts, loading spinners, and more.</p>
		<CodeBlock language="javascript" code={`import { ConicGradient } from '@brainandbones/skeleton';`} />
	</header>

	<!-- Examples -->
	<section class="space-y-4 md:space-y-0 md:grid md:grid-cols-3 md:gap-8">
		<!-- Tailwind Colors -->
		<div class="card card-body">
			<ConicGradient data={dataTailwindColors} legend={true}>
				<h3>Heat Map</h3>
			</ConicGradient>
		</div>
		<!-- CSS Properties -->
		<div class="card card-body">
			<ConicGradient data={dataColorVars} legend={true} />
		</div>
		<!-- Spinner -->
		<div class="card card-body flex justify-center items-center">
			<ConicGradient data={dataSpinner} spin={true} width="w-8">
				<small class="opacity-50">Loading</small>
			</ConicGradient>
		</div>
	</section>

	<!-- Usage -->
	<section class="space-y-4">
		<h2>Usage</h2>
		<p>Provde one more color stops that start at 0 and end at 100. The data set below will create a half red/green conic gradient.</p>
		<CodeBlock
			language="ts"
			code={`
import type { ConicColorStop } from '@brainandbones/skeleton';

const conicColorStops: ConicColorStop[] = [
	{ color: 'red', start: 0, end: 50 },
	{ color: 'green', start: 50, end: 100 }
];
        `}
		/>
		<CodeBlock language="html" code={`<ConicGradient data={conicColorStops} legend={false} spin={false}>(caption)</ConicGradient>`} />
		<!-- Legend -->
		<h3>Legend</h3>
		<p>A legend can be generated by setting <code>legend</code> as <em>true</em> and provided labels to each data set item.</p>
		<CodeBlock
			language="ts"
			code={`
const conicColorStops: ConicColorStop[] = [
	{ label: 'Label 1', color: 'red', start: 0, end: 33 },
	{ label: 'Label 2', color: 'green', start: 33, end: 66 },
	{ label: 'Label 3', color: 'blue', start: 66, end: 100 }
];
        `}
		/>
		<!-- Applying Colors -->
		<h3>Colors</h3>
		<h4>Via Theme Colors</h4>
		<p>To utilize your theme colors, you'll need to provide the theme color CSS custom property <code>var(--color-primary-500)</code> wrapped in <code>rgb()</code>.</p>
		<CodeBlock
			language="ts"
			code={`
const conicColorStops: ConicColorStop[] = [
	{ label: 'Primary', color: 'rgb(var(--color-primary-500))', start: 0, end: 33 },
	{ label: 'Acccent', color: 'rgb(var(--color-warning-500))', start: 33, end: 66 },
	{ label: 'Warning', color: 'rgb(var(--color-accent-500))', start: 66, end: 100 }
];
        `}
		/>
		<!-- Tailwind Colors -->
		<h4>Via Tailwind Colors</h4>
		<p>To utilize any default Tailwind colors, supply an array with the format <code>[name,shade]</code>.</p>
		<CodeBlock
			language="ts"
			code={`
const conicColorStops: ConicColorStop[] = [
	{ label: 'Orange', color: ['orange', 500], start: 0, end: 10 },
	{ label: 'Yellow', color: ['yellow', 500], start: 10, end: 35 },
	{ label: 'Red', color: ['red', 500], start: 35, end: 100 }
];
        `}
		/>
		<!-- Custom Colors -->
		<h4>Via Custom Colors</h4>
		<p>
			You can provide any <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color_value" target="_blank">standard CSS color value</a> as a string, including color names, hex, rgb/rgba, HSL, etc.
		</p>
		<CodeBlock
			language="ts"
			code={`
const conicColorStops: ConicColorStop[] = [
	{ label: 'Name', color: 'orange', start: 0, end: 10 },
	{ label: 'HSL', color: 'hsl(60deg 100% 50%)', start: 10, end: 35 },
	{ label: 'Hex', color: '#bada55', start: 35, end: 100 }
];
        `}
		/>
		<h3>Spinner</h3>
		<p>
			To create a spinner, set <code>spin</code> to <em>true</em>, and created a smooth gradient transition between transparent and filled color stops. Note the numeric gap between stops.
		</p>
		<CodeBlock language="html" code={`<ConicGradient data={conicColorStops} spin={true} width="w-8" />`} />
		<CodeBlock
			language="ts"
			code={`
const conicColorStops: ConicColorStop[] = [
    { color: 'transparent', start: 0, end: 25 },
	{ color: 'grey', start: 75, end: 100 }
];
        `}
		/>
	</section>

	<!-- Properties -->
	<section class="space-y-4">
		<h2>Properties</h2>
		<DataTable headings={tableProps.headings} source={tableProps.source} />
	</section>

	<!-- Slots -->
	<section class="space-y-4">
		<h2>Slots</h2>
		<DataTable headings={tableSlots.headings} source={tableSlots.source} />
	</section>
</div>
