export { Dialog } from './modules/anatomy';
export type { DialogRootProps } from './anatomy/root.svelte';
export type { DialogRootContextProps } from './anatomy/root-context.svelte';
export type { DialogTriggerProps } from './anatomy/trigger.svelte';
export type { DialogBackdropProps } from './anatomy/backdrop.svelte';
export type { DialogPositionerProps } from './anatomy/positioner.svelte';
export type { DialogContentProps } from './anatomy/content.svelte';
export type { DialogTitleProps } from './anatomy/title.svelte';
export type { DialogDescriptionProps } from './anatomy/description.svelte';
export type { DialogCloseTriggerProps } from './anatomy/close-trigger.svelte';
export type { DialogRootContextType as DialogRootContext } from './modules/root-context';
